{% set converted_models = '../converted_models' %}
{% set log_dir = '../logs' %}
{% set exp_name = 'test' %}



paths:
  checkpoints: {{ log_dir }}/{{ exp_name }}/checkpoints
  log_dir: {{ log_dir }}/{{ exp_name }}/logs
  converted_models: {{ converted_models }}
  update_interval: 20
  data: /home/core4/data/CAVIAR/Browse1

net:
  one_feat_map: False
  head_channels: 24
  channels_dict:
    hm: 1
    wh: 2
    of: 2

train:
  mixed_precision: True
  batch_size: 32
  epochs: 200
  lr: 0.02
  weight_decay: 0.0
  #losses
  loss_weights:
    hm: 1
    wh: 0.25
    of: 1
  losses:
    hm: asl     # asl | focal
    wh: sl1     # sl1
    of: sl1     # sl1
  asl_params:
    gamma_p: 2
    gamma_n: 5
    margin: 0.05
  # scheduler 
  scheduler: ocp  # ocp | multi_step
  ocp_params:
    max_lr_pct: 0.2
  multi_params:
    milestones: []
    gamma: 0.1

  val_rate: 3     # rate of validation: epochs % val_rate 
  test_rate: 2    # rate of test: epochs % (val_rate * test_rate)
  num_workers: 0
  pin_memory: True

  transforms:
    a: 0