{% set converted_models = '../converted_models' %}
{% set data_dir = '/home/core4/data' %}
{% set log_dir = '../logs' %}
{% set exp_name = 'test_caviar_refine3' %}


paths:
  checkpoints: {{ log_dir }}/{{ exp_name }}/checkpoints
  log_dir: {{ log_dir }}/{{ exp_name }}/logs
  converted_models: {{ converted_models }}
  update_interval: 20

  caviar_dir: {{ data_dir }}/CAVIAR
  voc_dir: {{ data_dir }}/pascal_voc_seg/VOCdevkit/VOC2012
  virat_dir: {{ data_dir }}/virat/frames

net:
  one_feat_map: True
  upsample: 'interpolate'   # interpolate | conv
  strides: [4]
  head_channels: 24
  channels_dict:
    hm: 1
    wh: 2
    of: 2
  pretrained: True
  pretrained_model: '/home/core4/Documents/logs/test_voc/checkpoints/Epoch_199.pth'

train:   
  dataset: caviar   # caviar | voc
  mixed_precision: True
  batch_size: 128
  epochs: 500
  lr: 0.01
  weight_decay: 0.00001
  #losses
  loss_weights:
    hm: 1
    wh: 0.1
    of: 1
  losses:
    hm: asl     # asl | focal
    wh: sl1     # sl1
    of: sl1     # sl1
  asl_params:
    gamma_p: 2
    gamma_n: 5
    margin: 0.05
  # scheduler 
  scheduler: ocp  # ocp | multi_step
  ocp_params:
    max_lr_pct: 0.1
  multi_params:
    milestones: []
    gamma: 0.1

  val_rate: 2     # rate of validation: epochs % val_rate 
  test_rate: 1    # rate of test: epochs % (val_rate * test_rate)
  num_workers: 0
  pin_memory: True

  transforms:
    in_size: [320, 320]
    min_box: 10
